import { describe, it, expect } from 'vitest';
import { generatePrintGuide } from './printGuide';
import { computeBaseplateTiling } from './splitPlanner';
import { groupPiecesByFingerprint } from './pieceFingerprint';
import { assignGroupNames } from './pieceNaming';
import type { BaseplateParams } from '@/shared/types/bin';

function makeParams(overrides: Partial<BaseplateParams> = {}): BaseplateParams {
  return {
    width: 6,
    depth: 4,
    gridUnitMm: 42,
    magnetHoles: false,
    magnetDiameter: 6.5,
    magnetDepth: 2,
    paddingLeft: 0,
    paddingRight: 0,
    paddingFront: 0,
    paddingBack: 0,
    fractionalEdgeX: 'end',
    fractionalEdgeY: 'end',
    ...overrides,
  };
}

function buildGuide(params: BaseplateParams, printBed = 256) {
  const tiling = computeBaseplateTiling(params, printBed);
  const groups = groupPiecesByFingerprint(tiling.pieces, params);
  const groupNames = assignGroupNames(groups, tiling.pieces);
  return generatePrintGuide({
    tiling,
    groups,
    groupNames,
    parentParams: params,
    fileExtension: '.stl',
    baseFileName: 'gridfinity-baseplate',
  });
}

describe('generatePrintGuide', () => {
  it('generates a guide with header, piece table, and grid map', () => {
    const params = makeParams({
      width: 18,
      depth: 18,
      paddingLeft: 2,
      paddingRight: 2,
      paddingFront: 2,
      paddingBack: 2,
      magnetHoles: true,
    });
    const guide = buildGuide(params);

    expect(guide).toContain('Gridfinity Baseplate Print Guide');
    expect(guide).toContain('18 × 18');
    expect(guide).toContain('magnets');
    expect(guide).toContain('Assembly Layout');
    expect(guide).toContain('Front of drawer');
    expect(guide).toContain('Row 1');
    expect(guide).toContain('Col A');

    // Should contain mm dimensions
    expect(guide).toMatch(/\d+\.\d+ × \d+\.\d+ × \d+\.\d+ mm/);

    // Should mention copy counts
    expect(guide).toMatch(/Print \d+ cop(y|ies)/);
  });

  it('includes all piece positions in the guide', () => {
    const params = makeParams({ width: 12, depth: 12 });
    const tiling = computeBaseplateTiling(params, 256);
    const guide = buildGuide(params);

    for (const piece of tiling.pieces) {
      expect(guide).toContain(piece.label);
    }
  });

  it('generates valid guide for single-piece tiling', () => {
    const params = makeParams({ width: 3, depth: 3 });
    const guide = buildGuide(params);

    expect(guide).toContain('3 × 3');
    expect(guide).toContain('Print 1 copy');
  });

  it('includes footer with attribution', () => {
    const params = makeParams({ width: 12, depth: 12 });
    const guide = buildGuide(params);

    expect(guide).toContain('Generated by Gridfinity Layout Tool');
    expect(guide).toContain('gridfinity.xyz');
  });

  it('shows unique count in header for split baseplates', () => {
    const params = makeParams({
      width: 18,
      depth: 18,
      paddingLeft: 2,
      paddingRight: 2,
      paddingFront: 2,
      paddingBack: 2,
    });
    const guide = buildGuide(params);

    // Should show "X (Y unique)" format
    expect(guide).toMatch(/Total pieces: \d+\s+\(\d+ unique\)/);
  });

  it('lists padding details for padded pieces', () => {
    const params = makeParams({
      width: 12,
      depth: 12,
      paddingLeft: 3,
      paddingRight: 3,
      paddingFront: 3,
      paddingBack: 3,
    });
    const guide = buildGuide(params);

    expect(guide).toContain('padding:');
    expect(guide).toContain('3mm');
  });

  it('Size line includes dovetail tongue protrusion when connectorNubs is enabled (#1498)', () => {
    // 4×4 grid, no padding, dovetails on. 4 units * 42mm = 168mm slab.
    // Edge piece with one male join edge → bbox 168 + 1.5 = 169.5mm.
    const params = makeParams({
      width: 8,
      depth: 4,
      connectorNubs: true,
    });
    const guide = buildGuide(params);

    // Each piece (4 wide) has one male join edge with invertDovetails=false:
    // - left piece: right=join is female (no protrusion) → 168.0mm
    // - right piece: left=join is male (1.5mm protrusion) → 169.5mm
    expect(guide).toContain('168.0 × 168.0');
    expect(guide).toContain('169.5 × 168.0');
  });

  it('Size line counts BOTH-side tongues under preferIdenticalPieces (#1640)', () => {
    // Paired mode places a tongue on every join edge regardless of which side
    // is conventionally male. A 4-wide piece with one join edge previously
    // reported 168.0 or 169.5 depending on side; now both sides → 169.5.
    const params = makeParams({
      width: 8,
      depth: 4,
      connectorNubs: true,
      preferIdenticalPieces: true,
    });
    const guide = buildGuide(params);

    // Both pieces have exactly one join edge (8 = 4+4 split, no padding):
    // under paired mode that join carries a tongue → bbox = 168 + 1.5 = 169.5.
    expect(guide).toContain('169.5 × 168.0');
    expect(guide).not.toContain('168.0 × 168.0');
  });
});
