import { describe, it, expect } from 'vitest';
import { generatePrintGuide, generateStackPrintNote, generateMarginGuide } from './printGuide';
import { computeBaseplateTiling } from './splitPlanner';
import { groupPiecesByFingerprint } from './pieceFingerprint';
import { assignGroupNames } from './pieceNaming';
import { countConnectorKeys } from './connectorKeys';
import type { ResolvedBaseplateParams } from '@/shared/types/bin';

function makeParams(overrides: Partial<ResolvedBaseplateParams> = {}): ResolvedBaseplateParams {
  return {
    width: 6,
    depth: 4,
    gridUnitMm: 42,
    magnetHoles: false,
    magnetDiameter: 6.5,
    magnetDepth: 2,
    paddingLeft: 0,
    paddingRight: 0,
    paddingFront: 0,
    paddingBack: 0,
    fractionalEdgeX: 'end',
    fractionalEdgeY: 'end',
    ...overrides,
  };
}

function buildGuide(
  params: ResolvedBaseplateParams,
  printBed = 256,
  stackPrint?: ResolvedBaseplateParams['stackPrint']
) {
  const tiling = computeBaseplateTiling(params, printBed);
  const groups = groupPiecesByFingerprint(tiling.pieces, params);
  const groupNames = assignGroupNames(groups, tiling.pieces);
  return generatePrintGuide({
    tiling,
    groups,
    groupNames,
    parentParams: params,
    fileExtension: '.stl',
    baseFileName: 'gridfinity-baseplate',
    stackPrint,
  });
}

describe('generatePrintGuide', () => {
  it('generates a guide with header, piece table, and grid map', () => {
    const params = makeParams({
      width: 18,
      depth: 18,
      paddingLeft: 2,
      paddingRight: 2,
      paddingFront: 2,
      paddingBack: 2,
      magnetHoles: true,
    });
    const guide = buildGuide(params);

    expect(guide).toContain('Gridfinity Baseplate Print Guide');
    expect(guide).toContain('18 × 18');
    expect(guide).toContain('magnets');
    expect(guide).toContain('Assembly Layout');
    expect(guide).toContain('Front of drawer');
    expect(guide).toContain('Row 1');
    expect(guide).toContain('Col A');

    // Should contain mm dimensions
    expect(guide).toMatch(/\d+\.\d+ × \d+\.\d+ × \d+\.\d+ mm/);

    // Each piece ships as its own file — the guide instructs printing every one.
    expect(guide).toMatch(/Print (this file|each of these \d+ files) once:/);
    expect(guide).toContain('ONE FILE PER PIECE');
  });

  it('lists one file per physical slot, named by grid label', () => {
    const params = makeParams({ width: 12, depth: 12 });
    const tiling = computeBaseplateTiling(params, 256);
    const guide = buildGuide(params);

    // Every drawer slot has its own file (e.g. gridfinity-baseplate_A1.stl),
    // not a single deduped file with a copy count.
    for (const piece of tiling.pieces) {
      expect(guide).toContain(`gridfinity-baseplate_${piece.label}.stl`);
    }
    expect(guide).not.toMatch(/Print \d+ copies →/);
  });

  it('includes all piece positions in the guide', () => {
    const params = makeParams({ width: 12, depth: 12 });
    const tiling = computeBaseplateTiling(params, 256);
    const guide = buildGuide(params);

    for (const piece of tiling.pieces) {
      expect(guide).toContain(piece.label);
    }
  });

  it('generates valid guide for single-piece tiling', () => {
    const params = makeParams({ width: 3, depth: 3 });
    const guide = buildGuide(params);

    expect(guide).toContain('3 × 3');
    expect(guide).toContain('Print this file once:');
  });

  it('includes footer with attribution', () => {
    const params = makeParams({ width: 12, depth: 12 });
    const guide = buildGuide(params);

    expect(guide).toContain('Generated by Gridfinity Layout Tool');
    expect(guide).toContain('gridfinitylayouttool.com');
  });

  it('shows unique count in header for split baseplates', () => {
    const params = makeParams({
      width: 18,
      depth: 18,
      paddingLeft: 2,
      paddingRight: 2,
      paddingFront: 2,
      paddingBack: 2,
    });
    const guide = buildGuide(params);

    // Should show "X (Y unique)" format
    expect(guide).toMatch(/Total pieces: \d+\s+\(\d+ unique\)/);
    // ...and the build-plate load count.
    expect(guide).toMatch(/Build-plate loads: \d+/);
  });

  it('lists padding details for padded pieces', () => {
    const params = makeParams({
      width: 12,
      depth: 12,
      paddingLeft: 3,
      paddingRight: 3,
      paddingFront: 3,
      paddingBack: 3,
    });
    const guide = buildGuide(params);

    expect(guide).toContain('padding:');
    expect(guide).toContain('3mm');
  });

  it('Size line includes dovetail tongue protrusion when connectorNubs is enabled (#1498)', () => {
    // 4×4 grid, no padding, dovetails on. 4 units * 42mm = 168mm slab.
    // Edge piece with one male join edge → bbox 168 + 1.5 = 169.5mm.
    const params = makeParams({
      width: 8,
      depth: 4,
      connectorNubs: true,
    });
    const guide = buildGuide(params);

    // Each piece (4 wide) has one male join edge with invertDovetails=false:
    // - left piece: right=join is female (no protrusion) → 168.0mm
    // - right piece: left=join is male (1.5mm protrusion) → 169.5mm
    expect(guide).toContain('168.0 × 168.0');
    expect(guide).toContain('169.5 × 168.0');
  });

  it('Size line counts BOTH-side tongues under preferIdenticalPieces (#1640)', () => {
    // Paired mode places a tongue on every join edge regardless of which side
    // is conventionally male. A 4-wide piece with one join edge previously
    // reported 168.0 or 169.5 depending on side; now both sides → 169.5.
    const params = makeParams({
      width: 8,
      depth: 4,
      connectorNubs: true,
      preferIdenticalPieces: true,
    });
    const guide = buildGuide(params);

    // Both pieces have exactly one join edge (8 = 4+4 split, no padding):
    // under paired mode that join carries a tongue → bbox = 168 + 1.5 = 169.5.
    expect(guide).toContain('169.5 × 168.0');
    expect(guide).not.toContain('168.0 × 168.0');
  });

  it('key mode reports flush plates (no tongue) and a connector-keys section', () => {
    const params = makeParams({
      width: 8,
      depth: 4,
      connectorNubs: true,
      connectorStyle: 'dovetailKey',
    });
    const tiling = computeBaseplateTiling(params, 256);
    const groups = groupPiecesByFingerprint(tiling.pieces, params);
    const groupNames = assignGroupNames(groups, tiling.pieces);
    const keyCount = countConnectorKeys(tiling, params);
    const guide = generatePrintGuide({
      tiling,
      groups,
      groupNames,
      parentParams: params,
      fileExtension: '.stl',
      baseFileName: 'gridfinity-baseplate',
      connectorKey: { fileName: 'gridfinity-baseplate_key.stl', count: keyCount },
    });

    // Both seam edges are female → plates are flush, no 1.5mm tongue protrusion.
    expect(guide).toContain('168.0 × 168.0');
    expect(guide).not.toContain('169.5');

    // Header + key section.
    expect(guide).toContain('puzzle key connectors');
    expect(guide).toContain('Connector keys');
    expect(guide).toContain('gridfinity-baseplate_key.stl');
    expect(guide).toContain('Hammer one into each seam junction');
    expect(keyCount).toBeGreaterThan(0);
  });

  it('snap-clip mode reports flush plates and a snap-clip-specific key section (#1610)', () => {
    const params = makeParams({
      width: 8,
      depth: 4,
      connectorNubs: true,
      connectorStyle: 'snapClip',
    });
    const tiling = computeBaseplateTiling(params, 256);
    const groups = groupPiecesByFingerprint(tiling.pieces, params);
    const groupNames = assignGroupNames(groups, tiling.pieces);
    const keyCount = countConnectorKeys(tiling, params);
    const guide = generatePrintGuide({
      tiling,
      groups,
      groupNames,
      parentParams: params,
      fileExtension: '.stl',
      baseFileName: 'gridfinity-baseplate',
      connectorKey: { fileName: 'gridfinity-baseplate_key.stl', count: keyCount },
    });

    // Female pockets on both seam sides → flush plates, no 1.5mm tongue.
    expect(guide).toContain('168.0 × 168.0');
    expect(guide).not.toContain('169.5');

    // Snap-clip-specific copy, NOT the dovetail wording.
    expect(guide).toContain('snap clip connectors');
    expect(guide).toContain('snap_clip (');
    expect(guide).toContain('until it clicks');
    expect(guide).toContain('barbs print in-plane');
    expect(guide).not.toContain('Hammer one into each seam junction');
    expect(guide).not.toContain('puzzle_key (');
    expect(keyCount).toBeGreaterThan(0);

    // Fit note uses the snap-clip per-side clearance (0.1), not the dovetail key's.
    expect(guide).toContain('0.20mm total clearance');
  });

  // issue #2024 — the connector fit offset must surface in the guide.
  it('omits a connector-fit line when the offset is zero', () => {
    const guide = buildGuide(makeParams({ width: 8, depth: 4, connectorNubs: true }));
    expect(guide).not.toContain('Connector fit:');
  });

  it('surfaces a non-zero connector-fit offset in the header for integral dovetails', () => {
    const guide = buildGuide(
      makeParams({ width: 8, depth: 4, connectorNubs: true, connectorFitOffset: 0.1 })
    );
    // Per-side clearance = nominal 0.15 + 0.1 = 0.25mm.
    expect(guide).toContain('Connector fit: +0.10mm');
    expect(guide).toContain('0.250mm per-side clearance');
  });

  it('reflects the offset in the dovetail-key total clearance note', () => {
    const params = makeParams({
      width: 8,
      depth: 4,
      connectorNubs: true,
      connectorStyle: 'dovetailKey',
      connectorFitOffset: 0.05,
    });
    const tiling = computeBaseplateTiling(params, 256);
    const groups = groupPiecesByFingerprint(tiling.pieces, params);
    const groupNames = assignGroupNames(groups, tiling.pieces);
    const guide = generatePrintGuide({
      tiling,
      groups,
      groupNames,
      parentParams: params,
      fileExtension: '.stl',
      baseFileName: 'gridfinity-baseplate',
      connectorKey: { fileName: 'k.stl', count: countConnectorKeys(tiling, params) },
    });
    // Key base clearance 0.075 + 0.05 = 0.125/side → 0.25mm total.
    expect(guide).toContain('Fit offset +0.05mm applied');
    expect(guide).toContain('0.25mm total clearance');
  });

  it('describes stacked towers, orientation, and the air-gap workflow when stacking', () => {
    // 18×18 with 2mm padding splits into multiple identical pieces.
    const params = makeParams({
      width: 18,
      depth: 18,
      paddingLeft: 2,
      paddingRight: 2,
      paddingFront: 2,
      paddingBack: 2,
    });
    const guide = buildGuide(params, 256, {
      enabled: true,
      gapMm: 0.2 as never,
    });

    expect(guide).toContain('Stack printing');
    expect(guide).toContain('right-side up'); // bottom plate upright
    expect(guide).toContain('flipped upside'); // the rest flipped
    expect(guide).toContain('air gap');
    expect(guide).toContain('support interface'); // PETG / slicer tip
    expect(guide).toContain('print once =');
    expect(guide).toContain('Assembles:');
    // The misleading "Print N copies" instruction must NOT appear when stacking.
    expect(guide).not.toMatch(/Print \d+ copies →/);
  });

  it('multiplies stacked plate counts by the copies multiplier', () => {
    // A small layout is a single un-split piece; copies turns it into a tower.
    const params = makeParams({ width: 4, depth: 4 });
    const tiling = computeBaseplateTiling(params, 256);
    const groups = groupPiecesByFingerprint(tiling.pieces, params);
    const groupNames = assignGroupNames(groups, tiling.pieces);
    const guideWith = (copies: number) =>
      generatePrintGuide({
        tiling,
        groups,
        groupNames,
        parentParams: params,
        fileExtension: '.stl',
        baseFileName: 'bp',
        stackPrint: { enabled: true, gapMm: 0.2 as never, copies },
        copies,
      });

    expect(guideWith(1)).toContain('print once = 1 plate');
    expect(guideWith(3)).toContain('print once = 3 plates');
  });

  it('generateStackPrintNote produces a standalone stacking note', () => {
    const note = generateStackPrintNote({
      enabled: true,
      gapMm: 0.2 as never,
    });
    expect(note).toContain('Stack printing');
    expect(note).toContain('air gap');
    expect(note).toContain('support interface');
    expect(note).toContain('Generated by Gridfinity Layout Tool');
  });

  it('generateStackPrintNote appends a margin section when rails ship alongside (#2641)', () => {
    const rails = [
      { fileName: 'plate_margin-right.stl', side: 'right', lengthMm: 126, bandThicknessMm: 10 },
    ];
    const note = generateStackPrintNote({ enabled: true, gapMm: 0.2 as never }, rails);
    expect(note).toContain('Stack printing');
    expect(note).toContain('Detached margins');
    expect(note).toContain('plate_margin-right.stl');
    // The footer stays last.
    expect(note.indexOf('Detached margins')).toBeLessThan(note.indexOf('Generated by'));
    // Towers bake in every copy but rails ship one file each, so the multiplier
    // must surface as a per-rail print count — and only when it multiplies.
    expect(note).not.toContain('Print each rail file');
    const multi = generateStackPrintNote({ enabled: true, gapMm: 0.2 as never }, rails, 3);
    expect(multi).toContain('Print each rail file 3 times');
  });

  it('generateMarginGuide lists each detached rail file with its dimensions', () => {
    const guide = generateMarginGuide([
      { fileName: 'plate_margin-front.stl', side: 'front', lengthMm: 188, bandThicknessMm: 10 },
      { fileName: 'plate_margin-left.stl', side: 'left', lengthMm: 126, bandThicknessMm: 10 },
    ]);
    expect(guide).toContain('Detached margins');
    expect(guide).toContain('plate_margin-front.stl');
    expect(guide).toContain('front, 188.0 × 10.0 mm');
    expect(guide).toContain('plate_margin-left.stl');
    expect(guide).toContain('Generated by Gridfinity Layout Tool');
  });

  it('includes the widen-the-gap step only when the gap is too tight (< 0.4mm)', () => {
    const tight = generateStackPrintNote({ enabled: true, gapMm: 0.2 as never });
    expect(tight).toContain("set this tool's Gap to about 0.4mm");
    expect(tight).toMatch(/1\. Give the interface room/);

    // Once the user has already widened the gap, the self-referential step is
    // dropped and the remaining steps renumber from 1.
    const wide = generateStackPrintNote({ enabled: true, gapMm: 0.5 as never });
    expect(wide).not.toContain("set this tool's Gap to about 0.4mm");
    expect(wide).toMatch(/1\. Load the non-stick filament/);
  });
});
